name: markmeapp
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4
  permission_handler: ^11.0.1

  # Dio
  dio: ^5.4.0

  # Navigation
  go_router: ^14.0.2

  google_fonts: ^6.2.1

  # State management
  flutter_riverpod: ^2.5.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Flutter env
  flutter_dotenv: ^5.1.0

  #Flutter SVG
  flutter_svg: ^2.0.9

  # HTTP requests for backend API communication
  http: ^1.1.0

  # JSON serialization for API data models
  json_annotation: ^4.8.1

  # UI
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^17.0.0
  device_info_plus: ^12.2.0
  debounce_throttle: ^2.0.0
  camera: ^0.11.3
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  multi_dropdown: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation for JSON serialization
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

  flutter_lints: ^5.0.0
  provider: ^6.0.5

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
